import fs from "fs";
import path from "path";

const resultsDir = path.join(process.cwd(), "tests/audit/results");
const jsonPath = path.join(resultsDir, "results.json");
const reportPath = path.join(resultsDir, "report.md");
const screenshotsDir = path.join(resultsDir, "screenshots");

interface TestResult {
  title: string;
  status: "passed" | "failed" | "timedOut" | "skipped" | "interrupted";
  duration: number;
  errors?: { message: string; stack?: string }[];
}

interface Suite {
  title: string;
  tests?: TestResult[];
  suites?: Suite[];
}

interface ResultsJson {
  suites?: Suite[];
  errors?: { message: string; stack?: string }[];
  stats?: {
    total: number;
    expected: number;
    unexpected: number;
    flaky: number;
    skipped: number;
    duration: number;
  };
}

function flattenTests(suite: Suite): TestResult[] {
  const out: TestResult[] = [];
  if (suite.tests) out.push(...suite.tests);
  if (suite.suites) {
    for (const s of suite.suites) out.push(...flattenTests(s));
  }
  return out;
}

function getScreenshots() {
  if (!fs.existsSync(screenshotsDir)) return [];
  return fs
    .readdirSync(screenshotsDir)
    .filter((f) => f.endsWith(".png"))
    .sort();
}

function generateReport() {
  if (!fs.existsSync(jsonPath)) {
    console.error(`No results file found at ${jsonPath}. Run "npm run audit" first.`);
    process.exit(1);
  }

  const results: ResultsJson = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
  const allTests = results.suites ? results.suites.flatMap(flattenTests) : [];
  const passed = allTests.filter((t) => t.status === "passed");
  const failed = allTests.filter((t) => t.status === "failed" || t.status === "timedOut");
  const skipped = allTests.filter((t) => t.status === "skipped" || t.status === "interrupted");

  const screenshots = getScreenshots();

  let md = `# Additv Prototype — AI Bug-Finding Audit Report\n\n`;
  md += `Generated: ${new Date().toISOString()}\n\n`;

  md += `## Summary\n\n`;
  md += `- **Total scenarios:** ${allTests.length}\n`;
  md += `- **Passed:** ${passed.length}\n`;
  md += `- **Failed:** ${failed.length}\n`;
  md += `- **Skipped:** ${skipped.length}\n`;
  md += `- **Screenshots captured:** ${screenshots.length}\n\n`;

  if (failed.length > 0) {
    md += `## Failures\n\n`;
    for (const test of failed) {
      md += `### ❌ ${test.title}\n\n`;
      if (test.errors && test.errors.length > 0) {
        for (const err of test.errors) {
          md += `\`\`\`\n${err.message}\n${err.stack ?? ""}\n\`\`\`\n\n`;
        }
      } else {
        md += `No error message captured.\n\n`;
      }
    }
  }

  if (failed.length === 0) {
    md += `## Result\n\n✅ All audited scenarios passed without console errors or NaN values.\n\n`;
  }

  md += `## Screenshots\n\n`;
  if (screenshots.length === 0) {
    md += `No screenshots captured.\n`;
  } else {
    for (const file of screenshots) {
      md += `- \`${file}\`\n`;
    }
  }

  md += `\n---\n\n`;
  md += `*This report was generated by the Additv AI bug-finding audit harness.*\n`;

  fs.writeFileSync(reportPath, md);
  console.log(`Report written to ${reportPath}`);
  console.log(`Passed: ${passed.length}, Failed: ${failed.length}, Skipped: ${skipped.length}`);
}

generateReport();
