/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemAdminRouteImport } from './routes/system-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as ReportsPerformanceRouteImport } from './routes/reports.performance'
import { Route as PaymentsTransactionsRouteImport } from './routes/payments.transactions'
import { Route as PaymentsMethodsRouteImport } from './routes/payments.methods'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'

const SystemAdminRoute = SystemAdminRouteImport.update({
  id: '/system-admin',
  path: '/system-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPerformanceRoute = ReportsPerformanceRouteImport.update({
  id: '/reports/performance',
  path: '/reports/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsTransactionsRoute = PaymentsTransactionsRouteImport.update({
  id: '/payments/transactions',
  path: '/payments/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsMethodsRoute = PaymentsMethodsRouteImport.update({
  id: '/payments/methods',
  path: '/payments/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-admin': typeof SystemAdminRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/payments/methods': typeof PaymentsMethodsRoute
  '/payments/transactions': typeof PaymentsTransactionsRoute
  '/reports/performance': typeof ReportsPerformanceRoute
  '/settings/team': typeof SettingsTeamRoute
  '/campaigns/': typeof CampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-admin': typeof SystemAdminRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/payments/methods': typeof PaymentsMethodsRoute
  '/payments/transactions': typeof PaymentsTransactionsRoute
  '/reports/performance': typeof ReportsPerformanceRoute
  '/settings/team': typeof SettingsTeamRoute
  '/campaigns': typeof CampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-admin': typeof SystemAdminRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/payments/methods': typeof PaymentsMethodsRoute
  '/payments/transactions': typeof PaymentsTransactionsRoute
  '/reports/performance': typeof ReportsPerformanceRoute
  '/settings/team': typeof SettingsTeamRoute
  '/campaigns/': typeof CampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/system-admin'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/payments/methods'
    | '/payments/transactions'
    | '/reports/performance'
    | '/settings/team'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/system-admin'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/payments/methods'
    | '/payments/transactions'
    | '/reports/performance'
    | '/settings/team'
    | '/campaigns'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/system-admin'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/payments/methods'
    | '/payments/transactions'
    | '/reports/performance'
    | '/settings/team'
    | '/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SystemAdminRoute: typeof SystemAdminRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  PaymentsMethodsRoute: typeof PaymentsMethodsRoute
  PaymentsTransactionsRoute: typeof PaymentsTransactionsRoute
  ReportsPerformanceRoute: typeof ReportsPerformanceRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-admin': {
      id: '/system-admin'
      path: '/system-admin'
      fullPath: '/system-admin'
      preLoaderRoute: typeof SystemAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/performance': {
      id: '/reports/performance'
      path: '/reports/performance'
      fullPath: '/reports/performance'
      preLoaderRoute: typeof ReportsPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/transactions': {
      id: '/payments/transactions'
      path: '/payments/transactions'
      fullPath: '/payments/transactions'
      preLoaderRoute: typeof PaymentsTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/methods': {
      id: '/payments/methods'
      path: '/payments/methods'
      fullPath: '/payments/methods'
      preLoaderRoute: typeof PaymentsMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SystemAdminRoute: SystemAdminRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  PaymentsMethodsRoute: PaymentsMethodsRoute,
  PaymentsTransactionsRoute: PaymentsTransactionsRoute,
  ReportsPerformanceRoute: ReportsPerformanceRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
